import { defineConfig } from "oxlint"

export default defineConfig({
  options: { typeAware: true },
  plugins: [
    "eslint",
    "typescript",
    "unicorn",
    "import",
    "oxc",
    "promise",
    "vitest",
    "jest",
    "effecttsgo",
  ],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
    {
      name: "anti-slop-effect",
      specifier: "./tools/oxlint/anti-slop/effect/index.ts",
    },
  ],
  categories: {
    correctness: "error",
    nursery: "off",
    pedantic: "error",
    perf: "error",
    restriction: "error",
    style: "error",
    suspicious: "error",
  },
  ignorePatterns: [
    ".agent/**",
    ".agents/**",
    ".claude/**",
    ".codex/**",
    ".continue/**",
    ".cursor/**",
    ".gemini/**",
    ".opencode/**",
    ".pi/**",
    ".roo/**",
    ".windsurf/**",
    "tools/oxlint/anti-slop/**",
    "node_modules/**",
    "dist/**",
    "fixtures/**",
  ],
  rules: {
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
    "anti-slop-effect/no-service-constructor-imports": "error",
    "arrow-body-style": "off",
    "capitalized-comments": "off",
    "typescript/consistent-return": "off",
    "default-case": "off",
    "effecttsgo/async-function": "off",
    "effecttsgo/crypto-random-uuid-in-effect": "off",
    "effecttsgo/crypto-random-uuid": "off",
    "effecttsgo/global-random": "off",
    "effecttsgo/missing-pipeable-signature": "off",
    "effecttsgo/node-builtin-import": "off",
    "effecttsgo/prefer-schema-over-json": "off",
    "effecttsgo/process-env": "off",
    "effecttsgo/return-effect-in-gen": "off",
    "effecttsgo/strict-boolean-expressions": "off",
    "effecttsgo/strict-effect-provide": "off",
    "effecttsgo/unsafe-effect-type-assertion": "off",
    "eslint-plugin-import/namespace": "off",
    "eslint/array-callback-return": "off",
    "eslint/class-methods-use-this": "off",
    "eslint/new-cap": "off",
    // The imported base rule produces 1,169 declaration-only findings in the
    // existing code. Keep declaration grouping as a local readability choice.
    "eslint/one-var": "off",
    "eslint/no-unused-vars": "off",
    "eslint/no-use-before-define": "off",
    "eslint/prefer-rest-params": "off",
    "func-names": "off",
    "func-style": "off",
    "id-length": "off",
    "import/consistent-type-specifier-style": "off",
    "import/exports-last": "off",
    "import/extensions": ["error", "always", { ignorePackages: true }],
    "import/first": "error",
    "import/group-exports": "off",
    "import/max-dependencies": "off",
    "import/no-absolute-path": "error",
    "import/no-amd": "error",
    "import/no-anonymous-default-export": "off",
    "import/no-commonjs": "error",
    "import/no-cycle": ["error", { ignoreTypes: true }],
    "import/no-default-export": "off",
    "import/no-duplicates": ["error", { preferInline: true }],
    "import/no-empty-named-blocks": "off",
    "import/no-mutable-exports": "error",
    "import/no-named-default": "error",
    "import/no-named-export": "off",
    "import/no-namespace": "off",
    "import/no-nodejs-modules": "off",
    "import/no-relative-parent-imports": "off",
    "import/no-self-import": "error",
    "import/no-unassigned-import": "off",
    "import/no-webpack-loader-syntax": "error",
    "import/prefer-default-export": "off",
    "import/unambiguous": "off",
    "init-declarations": "off",
    "jest/prefer-ending-with-an-expect": "off",
    "jest/prefer-expect-assertions": "off",
    "jest/no-standalone-expect": "off",
    "jest/require-hook": "off",
    "jest/valid-title": "off",
    "max-classes-per-file": "off",
    "max-depth": "off",
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-params": "off",
    "max-statements": "off",
    "no-alert": "error",
    "no-console": "off",
    // Flags dead fallbacks (`?? x` on non-nullish operands) and impossible
    // conditions; requires typeAware.
    "typescript/no-unnecessary-condition": "error",
    "no-continue": "off",
    "no-duplicate-imports": "error",
    "no-else-return": "off",
    "no-empty": "off",
    "no-empty-function": "error",
    "no-implicit-coercion": "off",
    "no-inline-comments": "off",
    "no-magic-numbers": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-param-reassign": "off",
    "no-plusplus": "off",
    "no-proto": "error",
    "no-script-url": "error",
    "no-sequences": "error",
    "no-shadow": "off",
    "no-ternary": "off",
    "no-throw-literal": "off",
    "no-undef": "off",
    "no-undefined": "off",
    "no-underscore-dangle": "off",
    "no-use-before-define": "off",
    "no-useless-return": "off",
    "no-var": "error",
    "no-void": "off",
    "no-warning-comments": "off",
    "oxc/no-async-await": "off",
    "oxc/no-barrel-file": "off",
    "oxc/no-map-spread": "off",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "prefer-const": "off",
    "prefer-destructuring": "off",
    "promise/always-return": "error",
    "promise/catch-or-return": "off",
    "promise/no-multiple-resolved": "error",
    "promise/no-nesting": "error",
    "promise/no-new-statics": "error",
    "promise/no-promise-in-callback": "error",
    "promise/no-return-wrap": "error",
    "promise/param-names": "error",
    "promise/prefer-await-to-then": "off",
    "promise/prefer-catch": "error",
    "promise/valid-params": "error",
    "react/no-unstable-nested-components": "off",
    "require-await": "off",
    "require-yield": "off",
    "sort-imports": "off",
    "sort-keys": "off",
    "symbol-description": "off",
    "typescript/array-type": "off",
    "typescript/ban-ts-comment": "off",
    "typescript/ban-types": "off",
    "typescript/consistent-indexed-object-style": "off",
    "typescript/consistent-type-definitions": "off",
    "typescript/consistent-type-imports": [
      "error",
      { prefer: "type-imports", fixStyle: "inline-type-imports" },
    ],
    "typescript/explicit-function-return-type": "off",
    "typescript/explicit-member-accessibility": "off",
    "typescript/explicit-module-boundary-types": "off",
    "typescript/no-dynamic-delete": "off",
    "typescript/no-duplicate-type-constituents": "off",
    "typescript/no-empty-object-type": "off",
    "typescript/no-explicit-any": "off",
    "typescript/no-floating-promises": "off",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-invalid-void-type": "off",
    "typescript/no-namespace": ["error", { allowDeclarations: true }],
    "typescript/no-confusing-void-expression": "off",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-assertion": "off",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-type-parameters": "off",
    "typescript/no-unsafe-type-assertion": "off",
    "typescript/no-use-before-define": "off",
    "typescript/no-var-requires": "error",
    "typescript/only-throw-error": "off",
    "typescript/prefer-ts-expect-error": "off",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/promise-function-async": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/strict-void-return": "off",
    "typescript/use-unknown-in-catch-callback-variable": "error",
    "unicorn/catch-error-name": ["error", { name: "cause" }],
    "unicorn/consistent-function-scoping": "off",
    "unicorn/explicit-length-check": "off",
    "unicorn/filename-case": "off",
    "unicorn/custom-error-definition": "off",
    "unicorn/max-nested-calls": "off",
    "unicorn/new-for-builtins": "off",
    "unicorn/no-abusive-eslint-disable": "off",
    "unicorn/no-anonymous-default-export": "off",
    "unicorn/no-array-callback-reference": "off",
    "unicorn/no-array-for-each": "off",
    "unicorn/no-array-method-this-argument": "off",
    "unicorn/no-array-reduce": "off",
    // Adding `u` can change the meaning of established regular expressions.
    "eslint/require-unicode-regexp": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-null": "off",
    "unicorn/no-object-as-default-parameter": "off",
    "unicorn/no-typeof-undefined": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/number-literal-case": "off",
    "unicorn/numeric-separators-style": "off",
    "unicorn/prefer-array-flat": "off",
    "unicorn/prefer-dom-node-append": "off",
    "unicorn/prefer-dom-node-remove": "off",
    "unicorn/prefer-global-this": "off",
    "unicorn/prefer-modern-math-apis": "error",
    // Existing code intentionally preserves mutation/order and ANSI escape spelling;
    // these style rules do not improve behavior without broad rewrites.
    "unicorn/no-array-sort": "off",
    "unicorn/no-array-reverse": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/prefer-at": "off",
    "unicorn/prefer-export-from": "off",
    "unicorn/prefer-single-call": "off",
    "unicorn/no-immediate-mutation": "off",
    "unicorn/no-lonely-if": "off",
    "typescript/prefer-for-of": "off",
    "unicorn/escape-case": "off",
    "unicorn/no-hex-escape": "off",
    "unicorn/import-style": "off",
    "unicorn/prefer-code-point": "off",
    "eslint/prefer-named-capture-group": "off",
    "eslint/no-bitwise": "off",
    "eslint/no-loop-func": "off",
    "eslint/no-lonely-if": "off",
    "eslint/no-template-curly-in-string": "off",
    "eslint/prefer-template": "off",
    // Namespace exports contain runtime members; this rule misclassifies them as type-only.
    "typescript/consistent-type-exports": "off",
    "jest/prefer-lowercase-title": "off",
    "vitest/prefer-lowercase-title": "off",
    "promise/prefer-await-to-callbacks": "off",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-number-properties": "off",
    "unicorn/prefer-optional-catch-binding": "off",
    "unicorn/prefer-query-selector": "off",
    "unicorn/prefer-set-has": "off",
    "unicorn/prefer-spread": "off",
    "unicorn/prefer-string-raw": "off",
    "unicorn/prefer-string-replace-all": "off",
    "unicorn/prefer-top-level-await": "off",
    "unicorn/require-module-specifiers": "off",
    "unicorn/require-post-message-target-origin": "off",
    "unicorn/switch-case-braces": "off",
    "unicorn/throw-new-error": "off",
    "vitest/no-conditional-tests": "off",
    "vitest/no-importing-vitest-globals": "off",
    "vitest/no-import-node-test": "error",
    "vitest/no-standalone-expect": "off",
    "vitest/prefer-called-once": "error",
    "vitest/prefer-called-times": "error",
    "vitest/prefer-expect-assertions": "off",
    "vitest/prefer-expect-type-of": "error",
    "vitest/prefer-importing-vitest-globals": "off",
    "vitest/prefer-strict-boolean-matchers": "off",
    "vitest/prefer-to-be-falsy": "off",
    "vitest/prefer-to-be-object": "error",
    "vitest/prefer-to-be-truthy": "off",
    "vitest/require-hook": "off",
    "vitest/require-test-timeout": "off",
    "vitest/require-local-test-context-for-concurrent-snapshots": "error",
    "vitest/valid-title": "off",
    complexity: "off",
    curly: "off",
    eqeqeq: "error",
    radix: "off",
    "no-restricted-imports": [
      "error",
      {
        paths: [
          { name: "safemods", message: "Import the concrete source module inside the package." },
        ],
      },
    ],
  },
  overrides: [
    {
      files: ["tools/**/*.mjs"],
      // Standalone scripts are outside tsconfig; JSDoc would add noise without
      // changing their runtime contracts.
      rules: {
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-argument": "off",
        "typescript/no-unsafe-member-access": "off",
        "typescript/no-unsafe-call": "off",
        "typescript/no-unsafe-return": "off",
        "eslint/no-await-in-loop": "off",
        "unicorn/import-style": "off",
        "unicorn/no-await-expression-member": "off",
        "eslint/prefer-named-capture-group": "off",
        // Untyped JS: indexed accesses (process.argv, plain records) cannot be
        // proven nullable, yet they legitimately are at runtime.
        "typescript/no-unnecessary-condition": "off",
      },
    },
    {
      files: ["src/Pattern/**/*.ts"],
      rules: {
        "no-restricted-imports": ["error", { patterns: ["../Query/*", "../Query/**"] }],
      },
    },
    {
      files: ["src/Workspace/**/*.ts"],
      rules: {
        "no-restricted-imports": [
          "error",
          {
            patterns: [
              "../Draft/*",
              "../Edit/*",
              "../Plan/*",
              "../Overlay/*",
              "../Verification/*",
              "../Application/*",
            ],
          },
        ],
      },
    },
    {
      files: ["src/**/*.test.ts", "examples/**/*.ts"],
      rules: {
        "no-restricted-imports": "off",
        // Tests use @effect/vitest assertions and intentionally exercise
        // multiple outcomes in a single case; these Jest/Vitest defaults are
        // duplicate and incompatible with that test style.
        "jest/max-expects": "off",
        "jest/prefer-strict-equal": "off",
        "jest/prefer-to-have-length": "off",
        "vitest/max-expects": "off",
        "vitest/prefer-strict-equal": "off",
        "vitest/prefer-to-have-length": "off",
        "vitest/no-conditional-tests": "off",
        "vitest/no-conditional-in-test": "off",
        "vitest/no-conditional-expect": "off",
        "vitest/prefer-to-be-truthy": "off",
        "vitest/prefer-to-be-falsy": "off",
        "jest/no-conditional-in-test": "off",
        "jest/no-conditional-expect": "off",
        // Test fixtures deliberately inspect untyped Effect failures.
        "effecttsgo/any-unknown-in-error-context": "off",
        "effecttsgo/unknown-in-effect-catch": "off",
      },
    },
    {
      files: ["src/test/**/*.ts", "test/**/*.ts"],
      rules: {
        // Test fixtures deliberately inspect untyped Effect failures.
        "effecttsgo/any-unknown-in-error-context": "off",
        "effecttsgo/unknown-in-effect-catch": "off",
      },
    },
    {
      files: ["src/Cli/**/*.test.ts"],
      rules: {
        "typescript/no-unsafe-assignment": "off",
        "typescript/no-unsafe-member-access": "off",
        "typescript/no-unsafe-return": "off",
      },
    },
    {
      files: ["bin/**/*.ts", "tools/**/*.mjs", "examples/**/*.ts"],
      rules: {
        // These are human-facing scripts and examples; console output is
        // their API rather than application Effect logging.
        "effecttsgo/global-console": "off",
        "effecttsgo/global-console-in-effect": "off",
      },
    },
  ],
})
